services:
  api:
    build: .

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      CHROMA_DB_PATH: /app/chroma_db

    volumes:
      - chroma_data:/app/chroma_db

volumes:
  chroma_data:
